### ISSUE TITLE
Disable plugin checking

### ISSUE THREAD

**Issue by huaxibo** [kugge/Kaiiju#97]
Can plugin checking be disabled like the DirtyFolia branch?

**Comment by kaxonomy** [comment]
DirtyFolia is a meme.

**Comment by Fox2Code** [comment]
I thought about it a lot, and I don't think it's a good idea.  
Casual users will ask support for every non folia supported plugins in existence.

But I think with some work it's possible to make folia support more non-folia plugins.  
Though, I don't think Kaiiju is the right project for this.  

@kaxlabs go make your own fork of Kaiiju for this, if you are ready to deal with users demanding support off course.

**Comment by kaxonomy** [comment]
> I thought about it a lot, and I don't think it's a good idea.  
> Casual users will ask support for every non folia supported plugins in existence.
> 
> But I think with some work it's possible to make folia support more non-folia plugins.  
> Though, I don't think Kaiiju is the right project for this.  
> 
> @kaxlabs go make your own fork of Kaiiju for this, if you are ready to deal with users demanding support off course.

I agree it's a bad idea. I don't know why you think I support it.

**Comment by Fox2Code** [comment]
@kaxlabs for fun off course.

**Comment by RealTriassic** [comment]
I don't see any issue with having it as an option that people can toggle as long as there's enough warnings that no support is provided to people using this option and that things are very likely to break.

Freedom of choice is always very nice to have.

**Comment by kaxonomy** [comment]
> I don't see any issue with having it as an option that people can toggle as long as there's enough warnings that no support is provided to people using this option and that things are very likely to break.
> 
> Freedom of choice is always very nice to have.

The issue is less technical people are more likely inclined to use Folia incompatible plugins without understanding why they're incompatible which causes them to post more bug report issues in the wrong place. If someone wants to workaround the issue, they can unzip a plugin jar and add folia-compatible: true to the plugin yaml manually.

**Comment by BoyOrigin** [comment]
This is not a great idea, just like as @kaxlabs said. If they just added the toggle, it will not solve anything. It will not make anything different from the start since incompatible plugins is not working that way (They still need a certain APIs, take Main Thread's BukkitScheduler as example). If any of you want to use non-compatible plugins, then Kaiiju is not there for you.

**Comment by sofianedjerbi** [comment]
The thing is that I don't want Kaiiju to become the "folia if you want to use plugins" fork
